services:
  web:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8445:5173"
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      - NODE_ENV=development
